/**
 * Generates src/lib/map-data.ts from Natural Earth 50m data (world-atlas).
 * Run once (network needed): node scripts/generate-map.mjs
 * Western Sahara is rendered as unlabeled land (no border, no label) — neutral treatment.
 */
import { feature, mesh } from "topojson-client";
import { geoConicConformal, geoPath, geoCentroid } from "d3-geo";
import { writeFileSync } from "node:fs";

const REGION = ["Algeria", "Morocco", "Tunisia", "Libya", "Mauritania", "W. Sahara"];
const LABELED = ["Algeria", "Morocco", "Tunisia", "Libya", "Mauritania"];

const url = "https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json";
const topo = await (await fetch(url)).json();

const countries = feature(topo, topo.objects.countries).features;
const sel = countries.filter((f) => REGION.includes(f.properties.name));
if (sel.length !== REGION.length) {
  throw new Error("Missing countries: " + REGION.filter((n) => !sel.find((f) => f.properties.name === n)));
}

const projection = geoConicConformal().parallels([27, 35]).rotate([-6, 0]);
projection.fitExtent(
  [
    [14, 14],
    [746, 546],
  ],
  { type: "FeatureCollection", features: sel },
);
const path = geoPath(projection);

const land = sel.map((f) => path(f)).join(" ");

// Internal borders between the five labeled countries only (WS stays borderless).
const borderGeom = mesh(topo, topo.objects.countries, (a, b) => {
  const an = a.properties.name;
  const bn = b.properties.name;
  return (
    an !== bn &&
    an !== "W. Sahara" &&
    bn !== "W. Sahara" &&
    LABELED.includes(an) &&
    LABELED.includes(bn)
  );
});
const borders = path(borderGeom);

const centroids = Object.fromEntries(
  sel
    .filter((f) => LABELED.includes(f.properties.name))
    .map((f) => {
      const [x, y] = projection(geoCentroid(f)).map((v) => Math.round(v));
      return [f.properties.name, { x, y }];
    }),
);

const ts = `// AUTO-GENERATED by scripts/generate-map.mjs — Natural Earth 50m, Lambert conic conformal.
// Do not edit by hand; re-run the script instead.

export type MapLabelKey = "Algeria" | "Morocco" | "Tunisia" | "Libya" | "Mauritania";

export const mapRegion = {
  land: ${JSON.stringify(land)},
  borders: ${JSON.stringify(borders)},
  labelPositions: ${JSON.stringify(centroids, null, 2).replace(/"/g, "")} as Record<MapLabelKey, { x: number; y: number }>,
};
`;

writeFileSync(new URL("../src/lib/map-data.ts", import.meta.url), ts);
console.log("map-data.ts written. Centroids:", JSON.stringify(centroids));
